image: Visual Studio 2017
configuration: Release
platform:
  - Win32
  - x64
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  matrix:
    - LIBRW_PLATFORMS: NULL
    - LIBRW_PLATFORMS: GL3
    - LIBRW_PLATFORMS: D3D9
    - LIBRW_PLATFORMS: NULL;GL3;D3D9
install:
  - if %platform%==Win32 set VCPKG_TRIPLET=x86-windows-static
  - if %platform%==x64 set VCPKG_TRIPLET=x64-windows-static
  - if not "x%LIBRW_PLATFORMS:GL3=%"=="x%LIBRW_PLATFORMS%" vcpkg install glfw3:%VCPKG_TRIPLET% glew:%VCPKG_TRIPLET%
before_build:
  - mkdir build
  - cd build
  - if %platform%==Win32 set CMAKE_GENERATOR=Visual Studio 15 2017
  - if %platform%==x64 set CMAKE_GENERATOR=Visual Studio 15 2017 Win64
  - cmake .. -DLIBRW_TOOLS=ON -DLIBRW_INSTALL=ON -G"%CMAKE_GENERATOR%" -DVCPKG_TARGET_TRIPLET=%VCPKG_TRIPLET% -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DLIBRW_PLATFORMS=%LIBRW_PLATFORMS%
build:
  project: c:\projects\librw\build\librw.sln
  verbosity: minimal
after_build:
  - cd "%APPVEYOR_BUILD_FOLDER%\build"
  - cpack -C %CONFIGURATION% -G TXZ
  - appveyor PushArtifact librw.tar.xz
cache:
  C:\tools\vcpkg\installed\ -> .appveyor.yml
