linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker

matrix:
   include:
    - <<: *linux
      env: CONAN_DOCKER_IMAGE=conanio/gcc7-centos6-x86 ARCH=x86
    - <<: *linux
      env: CONAN_DOCKER_IMAGE=conanio/gcc7-centos6 ARCH=x86_64

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh

matrix:
  include:
  - os: linux
    env: librw_platform=null CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8
  - os: linux
    env: librw_platform=gl3 CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8
  - os: linux
    env: librw_platform=ps2 CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8
